### ISSUE TITLE
Use only web3 as dependency

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/web3.js-plugin-chainlink#1]
Importing types and functionality from a bunch of different web3 packages are making it hard to link web3 and test changes against the dev version of web3.

so instead of:
```
import Contract from "web3-contract";
import Web3 from "web3"
```
we should only have:
```
import web3 from "web3";

const contract = new web3.eth.Contract()
```
if we can't do that, we should raise an issue on the web3 repo to export missing functionality.

**Comment by spacesailor24** [comment]
So there's actually a misconception regarding the plugin's use of `web3` to re-declare the module:

```typescript
declare module 'web3' {
	interface Web3 {
		chainlink: ChainlinkPlugin;
	}
}
```

I don't think the above code is the responsibility of the plugin, it actually belongs to the user using the `ChainlinkPlugin`. The `registerPlugin` method exists on the `Web3Context` class and not `Web3`, so there's no guarantee `ChainlinkPlugin` is going to be added to a `Web3` instance

To explain this better, consider the following:

```typescript
import { Web3Context } from 'web3-core/dist/web3_context';

import { ChainlinkPlugin } from '../../src/index';

declare module 'web3-core' {
	interface Web3Context {
		chainlink: ChainlinkPlugin;
	}
}

describe('Chainlink Plugin Tests', () => {
	it('should register ChainlinkPlugin and make the getPrice call', async () => {
		const web3Context = new Web3Context('https://rpc.ankr.com/eth_rinkeby');
		web3Context.registerPlugin(new ChainlinkPlugin(AggregatorV3InterfaceABI, aggregatorAddress));
		const price = await web3Context.chainlink.getPrice();
		expect(Object.keys(price)).toEqual(
			expect.arrayContaining([
				'roundId',
				'answer',
				'startedAt',
				'updatedAt',
				'answeredInRound',
			]),
		);
	});
});
```

In this example there is no dependency on `Web3` package, only `web3-core` and `web3-eth-contract`
